<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.jacksonhua</groupId>
    <artifactId>whh-starter-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <groupId>io.github.jacksonhua</groupId>
  <artifactId>whh-common</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>whh-common</name>
  <description>公共类或组件</description>
  <url>https://github.com/Jacksonhua/whh-project</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>王豪华</name>
      <email>asd1194190200@qq.com</email>
    </developer>
  </developers>
  <!-- SCM信息 -->
  <scm>
    <connection>scm:git:git://github.com/Jacksonhua/whh-project.git</connection>
    <developerConnection>scm:git:ssh://github.com:Jacksonhua/whh-project.git</developerConnection>
    <url>https://github.com/Jacksonhua/whh-project</url>
  </scm>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>


  </dependencies>
  <build>
    <plugins>
      <plugin>

        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>

      </plugin>
    </plugins>
  </build>
</project>
